#!/bin/bash

# Script de démonstration K6
# Ce script vérifie si K6 est installé et affiche un exemple de résultat

echo "════════════════════════════════════════════════════════════════"
echo "  📊 K6 Load Testing - Vérification d'Installation"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Vérifier si K6 est installé
if command -v k6 &> /dev/null; then
    echo "✅ K6 est installé!"
    echo ""
    k6 version
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  🚀 Scripts de test disponibles:"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "1️⃣  Frontend Load Test"
    echo "    Commande: k6 run frontend-load-test.js"
    echo "    Durée: ~7 minutes | Users: 0→100"
    echo ""
    echo "2️⃣  Backend API Test"
    echo "    Commande: k6 run backend-api-load-test.js"
    echo "    Durée: ~3 minutes | Users: 0→50"
    echo ""
    echo "3️⃣  Stress Test"
    echo "    Commande: k6 run stress-test.js"
    echo "    Durée: ~8 minutes | Users: 0→300"
    echo ""
    echo "4️⃣  Spike Test (Black Friday)"
    echo "    Commande: k6 run spike-test.js"
    echo "    Durée: ~3 minutes | Spike: 10→200 en 10s!"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  📚 NPM Scripts (Plus facile):"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "  npm run test:frontend       → Test frontend local"
    echo "  npm run test:backend        → Test backend API"
    echo "  npm run test:stress         → Test de stress"
    echo "  npm run test:spike          → Test Black Friday"
    echo "  npm run test:all            → Tests complets"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  📖 Documentation:"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "  • DEMARRAGE_RAPIDE.md  → Guide pratique"
    echo "  • README.md            → Guide technique complet"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "🎯 Pour commencer immédiatement:"
    echo "   k6 run backend-api-load-test.js"
    echo ""
else
    echo "❌ K6 n'est pas encore installé!"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "  📦 Installation:"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "Option 1 (Recommandé): Script automatique"
    echo "  ./install-k6.sh"
    echo ""
    echo "Option 2: Via SNAP"
    echo "  sudo snap install k6"
    echo ""
    echo "Option 3: Via APT"
    echo "  sudo apt-get update && sudo apt-get install k6"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
fi
